language: c

compiler:
  - clang
  - gcc

script: "./configure && make && make check && make distcheck"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libexpat-dev
  - autoreconf -i
